// Builds a clean, print-ready HTML document listing a community's vendors with
// their contact details. Opened in a new window that auto-triggers the print
// dialog (see printFlyer / openPrintWindow, which just writes the doc).

const esc = (s = '') =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const STATUS_LABEL = {
  approved: 'Approved',
  pending:  'Pending',
  denied:   'Denied',
  revoked:  'Revoked',
}

/**
 * @param {object} community
 * @param {Array}  apps   - application records (businessName, contactName, contactPhone, contactEmail, serviceCategory, status)
 * @param {'approved'|'all'} scope
 */
export function buildVendorListHTML(community, apps, scope = 'approved') {
  const showStatus = scope === 'all'
  const title = `${community?.name || 'Community'} — ${scope === 'approved' ? 'Approved' : 'All'} Vendors`
  const printedOn = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  // De-dupe by vendorId, then sort by business name.
  const seen = new Set()
  const rows = [...apps]
    .filter((a) => (a.vendorId && !seen.has(a.vendorId) ? seen.add(a.vendorId) : !a.vendorId))
    .sort((a, b) => (a.businessName || a.contactName || '').localeCompare(b.businessName || b.contactName || ''))

  const bodyRows = rows.length
    ? rows.map((a) => `
      <tr>
        <td>
          <div class="biz">${esc(a.businessName || '—')}</div>
          ${a.serviceCategory ? `<div class="cat">${esc(a.serviceCategory)}</div>` : ''}
        </td>
        <td>${esc(a.contactName || '—')}</td>
        <td>${esc(a.contactPhone || '—')}</td>
        <td>${esc(a.contactEmail || '—')}</td>
        ${showStatus ? `<td><span class="pill ${esc(a.status || '')}">${esc(STATUS_LABEL[a.status] || a.status || '—')}</span></td>` : ''}
      </tr>`).join('')
    : `<tr><td colspan="${showStatus ? 5 : 4}" class="empty">No vendors to display.</td></tr>`

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${esc(title)}</title>
<style>
  * { box-sizing:border-box; margin:0; padding:0; -webkit-print-color-adjust:exact !important; print-color-adjust:exact !important; }
  body { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif; color:#111827; padding:32px 28px; }
  .head { border-bottom:3px solid #0d3f73; padding-bottom:14px; margin-bottom:18px; display:flex; align-items:flex-end; justify-content:space-between; gap:16px; }
  .head h1 { font-size:22px; font-weight:800; color:#0d3f73; }
  .head .sub { font-size:12px; color:#6b7280; margin-top:4px; }
  .head .meta { font-size:12px; color:#6b7280; text-align:right; white-space:nowrap; }
  .count { font-size:12px; color:#374151; margin-bottom:12px; font-weight:600; }
  table { width:100%; border-collapse:collapse; }
  thead th { text-align:left; font-size:10.5px; text-transform:uppercase; letter-spacing:.06em; color:#6b7280; border-bottom:2px solid #e5e7eb; padding:0 10px 8px; }
  tbody td { font-size:13px; color:#374151; padding:11px 10px; border-bottom:1px solid #f0f2f5; vertical-align:top; }
  tbody tr:nth-child(even) { background:#f9fafb; }
  .biz { font-weight:700; color:#111827; }
  .cat { font-size:11px; color:#6b7280; margin-top:2px; }
  .empty { text-align:center; color:#9ca3af; padding:28px; font-style:italic; }
  .pill { display:inline-block; font-size:10.5px; font-weight:700; padding:2px 8px; border-radius:9px; background:#eef2f6; color:#374151; }
  .pill.approved { background:#dcfce7; color:#15803d; }
  .pill.pending { background:#fef3c7; color:#b45309; }
  .pill.denied, .pill.revoked { background:#fee2e2; color:#b91c1c; }
  .foot { margin-top:22px; font-size:10.5px; color:#9ca3af; text-align:center; }
  @media print { body { padding:0; } @page { margin:0.6in; } thead { display:table-header-group; } tr { break-inside:avoid; } }
</style>
</head>
<body>
  <div class="head">
    <div>
      <h1>${esc(community?.name || 'Community')} — Vendor List</h1>
      <div class="sub">${scope === 'approved' ? 'Approved vendors' : 'All vendors'}${community?.address ? ' · ' + esc(community.address) : ''}</div>
    </div>
    <div class="meta">Printed ${printedOn}</div>
  </div>
  <div class="count">${rows.length} vendor${rows.length === 1 ? '' : 's'}</div>
  <table>
    <thead>
      <tr>
        <th>Business</th>
        <th>Contact</th>
        <th>Phone</th>
        <th>Email</th>
        ${showStatus ? '<th>Status</th>' : ''}
      </tr>
    </thead>
    <tbody>${bodyRows}</tbody>
  </table>
  <div class="foot">Generated by Vendor Hub · speak2vendors.com</div>
  <script>window.addEventListener('load',function(){setTimeout(function(){window.print()},250)})</script>
</body>
</html>`
}
